# Generated by Django 2.2.4 on 2020-03-08 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0002_auto_20200308_1141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='number',
        ),
    ]
