# Generated by Django 2.2.4 on 2020-03-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.IntegerField()),
                ('headline', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=10)),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
    ]
