# Generated by Django 2.2.4 on 2020-03-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='Id',
            new_name='number',
        ),
    ]
