# Generated by Django 2.2.4 on 2020-03-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyAPI', '0003_remove_news_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
